name: Build dev documentations

on:
  push:
    paths:
      - 'manual/**'
      - '.github/workflows/update-dev-manual.yml'
    branches:
      - master

jobs:
  build_dev_manual:
    name: Build developer documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
      - name: copy openapi
        id: openapi
        run: cp ./daikoku/public/swaggers/admin-api-openapi.yaml ./manual/static/admin-api-openapi.yaml
      - name: Generate dev documentation website
        id: doc
        run: |
          sh ./scripts/build.sh manual
          echo "::set-output name=diff::$(git diff --numstat | wc -l)"
      - name: Commit files
        run: |
          git config --local user.email "daikoku-github-actions@users.noreply.github.com"
          git config --local user.name "daikoku-github-actions"
          git add --all
          git commit -am "Update dev documentation"
      - name: Push documentation
        uses: ad-m/github-push-action@master
        with:
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN}}
